# Server Configuration
server.port=${PORT:8080}

# Datasource Configuration
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=SmartPlanner;encrypt=true;trustServerCertificate=true}

spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


# Error handling
server.error.include-message=always

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-1.5-flash}
